# 自定义服务端口
server:
  port: 9090




spring:
  datasource:
    url: jdbc:mysql://47.115.88.249:3306/test_pro?useUnicode=true&GMT=8&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
    maxIdle: 8
    initialSize: 10

  jpa:
    database: MYSQL  # 定义数据库
    showSql: true  # 是否展示sql
    hibernate:
      ddlAuto: update   # Hibernate ddl auto (create, create-drop, update) 自动生成或者创建订单
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy  # Naming strategy

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:       # Redis服务器连接密码（默认为空）
    timeout: 3000
    jedis:
      pool:
        maxActive: 20    # 连接池最大连接数（使用负值表示没有限制）
        maxWait: -1     # 连接池最大阻塞等待时间（使用负值表示没有限制）
        maxIdle: 10      # 连接池中的最大空闲连接
        minIdle: 0     # 连接池中的最小空闲连接



